# Generated by Django 5.2.7 on 2025-11-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Read More', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='service_images/')),
            ],
        ),
    ]
