# Generated by Django 5.2.7 on 2025-11-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('work_email', models.EmailField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('enquiry_type', models.CharField(choices=[('Corporate Travel', 'Corporate Travel'), ('Partnership', 'Partnership'), ('Support', 'Support'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
